export { default as AboutSection } from "./AboutSection/AboutSection"
export { default as ToolsSection } from "./ToolsSection/ToolsSection"
export { default as ProjectsSection } from "./ProjectsSection/ProjectsSection"
export { default as VideoResumeSection } from "./VideoResumeSection/VideoResumeSection"
export { default as GitTimelineSection } from "./GitTimelineSection/GitTimelineSection"
