name: Build and Push image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t genebit/portfolio:latest
    - name: Push the Docker image to Docker Hub
      run: |
      docker login -u genebit -p ${{ secrets.DOCKER_HUB_SECRET }}
      docker push genebit/portfolio:latest
