name: Build and Push image to Docker Hub

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . -t genebit/portfolio:latest
    
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_SECRET }}" | docker login -u genebit --password-stdin
    
    - name: Push the Docker image to Docker Hub
      run: docker push genebit/portfolio:latest
